version: '2'
services:
    jhipmessageapp-app:
        image: jhipmessageapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipmessageapp-mysql:3306/jhipmessageapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipmessageapp-mysql:
        extends:
            file: mysql.yml
            service: jhipmessageapp-mysql
